export default {
    "hardest": "5.13a",
    "average": "5.10c",
    "ticks": [
        {
            "routeId": 105753628,
            "date": "2019-08-26",
            "pitches": 1,
            "notes": "Jittery af",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117652060,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105753952,
            "date": "2019-08-25",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 117652058,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106882881,
            "date": "2019-08-25",
            "pitches": 1,
            "notes": "Focus on Traverse. Get left foot after second crux and then side pull out left",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117652057,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105757699,
            "date": "2019-08-18",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Flash",
            "tickId": 117610658,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105754246,
            "date": "2019-08-18",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 117610657,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105760131,
            "date": "2019-08-18",
            "pitches": 1,
            "notes": "Grabbed pinch ball instead of ledge. Crux was easy ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117610656,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106882881,
            "date": "2019-08-18",
            "pitches": 1,
            "notes": "Clean through roof to rest. \nI went left through roof but might easier to go more right. \nCrux is lock off on left hand.\nLeft hand way out, right hand on good inside. High right and rock, run next to next clip ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117610651,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105762201,
            "date": "2019-08-17",
            "pitches": 1,
            "notes": "Funky crux. High right foot and push into sloper",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117610655,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105753838,
            "date": "2019-08-17",
            "pitches": 1,
            "notes": "Rekt",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117610654,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105997439,
            "date": "2019-08-17",
            "pitches": 1,
            "notes": "Left low jug, right shallow pocket, left high side pull ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117610653,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105756046,
            "date": "2019-08-17",
            "pitches": 1,
            "notes": "How did I even fall last time ?",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 117610652,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105753400,
            "date": "2019-08-17",
            "pitches": 1,
            "notes": "Left undercling apex to high right. Clip from left slimp. Left hand to ball sloper, right hip on wall. Right intermediate, bump to triangle. Find duo, climb past next clip to left hand slot",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117610650,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106002073,
            "date": "2019-08-05",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117551331,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105985455,
            "date": "2019-08-05",
            "pitches": 1,
            "notes": "Left hand to \"mono\", right hand out right. ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117551330,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105756046,
            "date": "2019-08-05",
            "pitches": 1,
            "notes": "Crux fall ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117551329,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105753400,
            "date": "2019-08-05",
            "pitches": 1,
            "notes": "Rest bad. Crux hard. Flow flawless. ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117551325,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106515299,
            "date": "2019-08-03",
            "pitches": 1,
            "notes": "Have to figure out feet for crux. \nTraverse in for upper crux on some side pulls. ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117551328,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105753940,
            "date": "2019-08-03",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 117551327,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 105753391,
            "date": "2019-08-03",
            "pitches": 1,
            "notes": "Popped at the crux because I missed the low left hand side pull. Can use it to hit the good crimp with the right hand ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117551326,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105762684,
            "date": "2019-07-27",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 117509781,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105758080,
            "date": "2019-07-27",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 117509755,
            "userStars": 3,
            "userRating": "5.12a"
        },
        {
            "routeId": 105761265,
            "date": "2019-07-06",
            "pitches": 1,
            "notes": "Right hand dry fire at second bolt. Probably went too far right anyway ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117316091,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105761268,
            "date": "2019-07-06",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 117316090,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105760608,
            "date": "2019-07-06",
            "pitches": 1,
            "notes": "Slip at second bolt ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117316089,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105862660,
            "date": "2019-07-06",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 117316088,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105761262,
            "date": "2019-07-06",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Flash",
            "tickId": 117316087,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105759063,
            "date": "2019-07-04",
            "pitches": 1,
            "notes": "Both pitches. Bomber ",
            "style": "Follow",
            "leadStyle": "",
            "tickId": 117306450,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 110678580,
            "date": "2019-07-04",
            "pitches": 1,
            "notes": "Poppin crystals ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117306447,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105758044,
            "date": "2019-07-04",
            "pitches": 2,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 117306446,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106515299,
            "date": "2019-06-16",
            "pitches": 1,
            "notes": "Crux between bolts 3 and 4: bump right. \nCrux before last bolt: stay left, until right hand can get the jug",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117130103,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105753940,
            "date": "2019-06-16",
            "pitches": 1,
            "notes": "Clean - found a crimp on right side of the left ledge ",
            "style": "TR",
            "leadStyle": "",
            "tickId": 117130098,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 105753940,
            "date": "2019-06-15",
            "pitches": 1,
            "notes": "2 falls at upper crux. Barndoored off the jug ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117130097,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 105753391,
            "date": "2019-06-15",
            "pitches": 1,
            "notes": "1 take ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117130096,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106248461,
            "date": "2019-06-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 117130095,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106231707,
            "date": "2019-06-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Flash",
            "tickId": 117130094,
            "userStars": 2,
            "userRating": ""
        },
        {
            "routeId": 106252682,
            "date": "2019-06-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Flash",
            "tickId": 117130093,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106175311,
            "date": "2019-06-09",
            "pitches": 1,
            "notes": "",
            "style": "Solo",
            "leadStyle": "",
            "tickId": 117130102,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106183208,
            "date": "2019-06-09",
            "pitches": 1,
            "notes": "",
            "style": "Solo",
            "leadStyle": "",
            "tickId": 117130101,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105792449,
            "date": "2019-06-09",
            "pitches": 1,
            "notes": "Top out is hard ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 117130100,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105792476,
            "date": "2019-06-09",
            "pitches": 1,
            "notes": "",
            "style": "Solo",
            "leadStyle": "",
            "tickId": 117130099,
            "userStars": 2,
            "userRating": ""
        },
        {
            "routeId": 105792465,
            "date": "2019-06-09",
            "pitches": 1,
            "notes": "",
            "style": "Solo",
            "leadStyle": "",
            "tickId": 117130092,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 114195097,
            "date": "2019-04-14",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Flash",
            "tickId": 116732445,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 114195105,
            "date": "2019-04-14",
            "pitches": 1,
            "notes": "Tricky start. Climbing like Tommy ",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 116732443,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 116656907,
            "date": "2019-03-27",
            "pitches": 3,
            "notes": "",
            "style": "Send",
            "leadStyle": "",
            "tickId": 116658669,
            "userStars": 3,
            "userRating": "V0"
        },
        {
            "routeId": 116649582,
            "date": "2019-03-24",
            "pitches": 1,
            "notes": "",
            "style": "Send",
            "leadStyle": "",
            "tickId": 116649610,
            "userStars": 2,
            "userRating": "V0"
        },
        {
            "routeId": 106931832,
            "date": "2019-03-24",
            "pitches": 1,
            "notes": "",
            "style": "Solo",
            "leadStyle": "",
            "tickId": 116644170,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105748415,
            "date": "2019-03-23",
            "pitches": 1,
            "notes": "1 fall on slab below crux. Fall at crux. Need to work crux beta ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116644037,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 113970820,
            "date": "2019-03-23",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116644033,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 113892902,
            "date": "2019-03-23",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116644029,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 114981533,
            "date": "2019-03-23",
            "pitches": 1,
            "notes": "Start is brutal ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116644026,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 112511931,
            "date": "2019-03-23",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116644024,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105749461,
            "date": "2019-03-23",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116638764,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105759129,
            "date": "2019-02-02",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511069,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105752839,
            "date": "2019-02-02",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511064,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105752329,
            "date": "2019-02-02",
            "pitches": 1,
            "notes": "1 fall 1 take. Beta intensive, stay left",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116511054,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105753880,
            "date": "2019-02-02",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 116511046,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105892056,
            "date": "2019-01-27",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511136,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105788000,
            "date": "2019-01-27",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511135,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105808935,
            "date": "2019-01-27",
            "pitches": 1,
            "notes": "5 falls. puuumpy",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116511130,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105732374,
            "date": "2019-01-27",
            "pitches": 1,
            "notes": "2 falls",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116511129,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105923032,
            "date": "2019-01-27",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 116511127,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105732563,
            "date": "2019-01-27",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 116511126,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105732560,
            "date": "2019-01-27",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 116511125,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105732530,
            "date": "2019-01-27",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116499225,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105949670,
            "date": "2019-01-26",
            "pitches": 1,
            "notes": "1 fall",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116511123,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106601301,
            "date": "2019-01-26",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511118,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107424504,
            "date": "2019-01-26",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511117,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105732686,
            "date": "2019-01-26",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116499222,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105910331,
            "date": "2019-01-25",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511157,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106060595,
            "date": "2019-01-25",
            "pitches": 1,
            "notes": "Beta intensive. Very cool.",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116511114,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105885132,
            "date": "2019-01-25",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511111,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 111020664,
            "date": "2019-01-25",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511092,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107367973,
            "date": "2019-01-25",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511086,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105975221,
            "date": "2019-01-25",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511085,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105808935,
            "date": "2019-01-24",
            "pitches": 1,
            "notes": "3 bolts",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116511078,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105732374,
            "date": "2019-01-24",
            "pitches": 1,
            "notes": "4 falls. Long live the yak crack jug. ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116511076,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105923032,
            "date": "2019-01-24",
            "pitches": 1,
            "notes": "1 fall",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116511075,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105732566,
            "date": "2019-01-24",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511074,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105732563,
            "date": "2019-01-24",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511073,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105732560,
            "date": "2019-01-24",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116511071,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105748403,
            "date": "2018-11-09",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 116124345,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 105750487,
            "date": "2018-11-09",
            "pitches": 1,
            "notes": "1 fall over big roof. Couldn't find jug",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116124333,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105748397,
            "date": "2018-11-09",
            "pitches": 1,
            "notes": "4 falls. Slippery feet. ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 116124331,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 107906862,
            "date": "2018-10-20",
            "pitches": 1,
            "notes": "1 fall before last bolt. \n1 fall on crux. \nKneebar is tricky. ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115446780,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 111769220,
            "date": "2018-10-20",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 115443151,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106081922,
            "date": "2018-10-20",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 115443150,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 107906862,
            "date": "2018-10-20",
            "pitches": 1,
            "notes": "3 falls. Clipping last bolt is hard ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115443149,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106081931,
            "date": "2018-10-20",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115443146,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106604790,
            "date": "2018-10-19",
            "pitches": 1,
            "notes": "\"Fell\" at 4th. Cool moves ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115443145,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 106586504,
            "date": "2018-10-18",
            "pitches": 1,
            "notes": "Warm up",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115437521,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106333612,
            "date": "2018-10-18",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115437520,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106586504,
            "date": "2018-10-17",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 115434512,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106064500,
            "date": "2018-10-17",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115434503,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 106085043,
            "date": "2018-10-17",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115434502,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106061906,
            "date": "2018-10-17",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115434501,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106061920,
            "date": "2018-10-16",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 115434511,
            "userStars": -1,
            "userRating": "5.10b\/c"
        },
        {
            "routeId": 109480361,
            "date": "2018-10-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 115434510,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107892916,
            "date": "2018-10-15",
            "pitches": 1,
            "notes": "",
            "style": "TR",
            "leadStyle": "",
            "tickId": 115434509,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107892930,
            "date": "2018-10-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115434508,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106927822,
            "date": "2018-10-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115434507,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106927842,
            "date": "2018-10-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115434506,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106782060,
            "date": "2018-10-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115434505,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107379163,
            "date": "2018-10-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115434504,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 110293313,
            "date": "2018-10-13",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Flash",
            "tickId": 115419110,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106702950,
            "date": "2018-10-13",
            "pitches": 1,
            "notes": "3 falls. Fist jam is great ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115419109,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106577204,
            "date": "2018-10-13",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115419108,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106125118,
            "date": "2018-10-13",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115419107,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106125110,
            "date": "2018-10-13",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Flash",
            "tickId": 115419106,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106154626,
            "date": "2018-10-13",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115419100,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106125070,
            "date": "2018-10-13",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115419099,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 106885734,
            "date": "2018-10-12",
            "pitches": 1,
            "notes": "Cooked after Amarillo sunset ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115419105,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106885744,
            "date": "2018-10-12",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Flash",
            "tickId": 115419104,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106885753,
            "date": "2018-10-12",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Flash",
            "tickId": 115419103,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106286394,
            "date": "2018-10-12",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115419102,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106885779,
            "date": "2018-10-12",
            "pitches": 1,
            "notes": "Felt so easy",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115419101,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 108172884,
            "date": "2018-10-06",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 115397571,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 106888456,
            "date": "2018-10-06",
            "pitches": 1,
            "notes": "Fell at third clip and roof. Chossy and wet up top",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115397570,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106873934,
            "date": "2018-10-06",
            "pitches": 1,
            "notes": "Couldn't pull first roof. Last flake was easy ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115397569,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 106852135,
            "date": "2018-10-06",
            "pitches": 1,
            "notes": "To end of roof. Awesome climbing",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115397568,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 107583304,
            "date": "2018-09-29",
            "pitches": 1,
            "notes": "Made to second to last roof. Lay down ledge was cool ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115383557,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106494923,
            "date": "2018-09-29",
            "pitches": 1,
            "notes": "Made first roof. Needed to smear ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115383555,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 109033631,
            "date": "2018-09-29",
            "pitches": 1,
            "notes": "Also wet af.",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115383535,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 109023567,
            "date": "2018-09-29",
            "pitches": 1,
            "notes": "Wet af",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 115383534,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 108768800,
            "date": "2018-09-29",
            "pitches": 1,
            "notes": "1 fall after roof. Didn't commit to crimp ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115383529,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106759846,
            "date": "2018-09-29",
            "pitches": 1,
            "notes": "Wet. Pumpy. 2 falls. ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115383518,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106461172,
            "date": "2018-09-28",
            "pitches": 1,
            "notes": "Dnf. Traded RR pad for crux at fourth clip. Crimp at top are brutal ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 115383516,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105963848,
            "date": "2018-09-28",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 115383486,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106759834,
            "date": "2018-04-24",
            "pitches": 1,
            "notes": "",
            "style": "TR",
            "leadStyle": "",
            "tickId": 115169041,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105918469,
            "date": "2018-04-21",
            "pitches": 1,
            "notes": "First 11 onsight!",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 114295023,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106156848,
            "date": "2018-04-21",
            "pitches": 1,
            "notes": "Fell at crux cause no beta",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 114295022,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105918472,
            "date": "2018-04-21",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 114295014,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106886454,
            "date": "2018-04-20",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 114295030,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106852068,
            "date": "2018-04-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 114262864,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 109063118,
            "date": "2018-04-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 114262859,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106882167,
            "date": "2018-04-15",
            "pitches": 1,
            "notes": "2 falls at crux. 1 take before flake ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 114262855,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105966939,
            "date": "2018-04-14",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 114260225,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105944381,
            "date": "2018-04-14",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 114260212,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105966917,
            "date": "2018-04-14",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 114260211,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105966922,
            "date": "2018-04-14",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 114260210,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106895203,
            "date": "2018-04-14",
            "pitches": 1,
            "notes": "4 falls. Mainly at dead point moving right",
            "style": "TR",
            "leadStyle": "",
            "tickId": 114260209,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105944377,
            "date": "2018-04-14",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 114260207,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106461197,
            "date": "2018-04-14",
            "pitches": 1,
            "notes": "3 Takes 2 Falls",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 114260206,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105918466,
            "date": "2018-04-13",
            "pitches": 1,
            "notes": "Got to 3rd bolt. Made move to fourth but couldn’t clip ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 114257111,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106603133,
            "date": "2018-04-13",
            "pitches": 1,
            "notes": "1T 1F ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 114257099,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107094773,
            "date": "2018-04-13",
            "pitches": 1,
            "notes": "1 T",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 114257098,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105993751,
            "date": "2018-04-13",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 114257097,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105993756,
            "date": "2018-04-13",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 114257096,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 111412963,
            "date": "2017-10-21",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 113734365,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 112835534,
            "date": "2017-10-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 113712904,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 112835323,
            "date": "2017-10-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 113712903,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106960810,
            "date": "2017-10-15",
            "pitches": 1,
            "notes": "Pumpy af. Made it 5 bolts ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113709903,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106138609,
            "date": "2017-10-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 113709886,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106184767,
            "date": "2017-10-15",
            "pitches": 1,
            "notes": "2 falls on traverse. Best route in Sandstonia ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113709880,
            "userStars": 4,
            "userRating": "5.10b"
        },
        {
            "routeId": 106138634,
            "date": "2017-10-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 113709870,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106138628,
            "date": "2017-10-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 113709866,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105987545,
            "date": "2017-10-15",
            "pitches": 1,
            "notes": "Gnarly roof ",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 113709859,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106418047,
            "date": "2017-10-15",
            "pitches": 1,
            "notes": "Fun flakes ",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 113709853,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 111054408,
            "date": "2017-10-13",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 113712902,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 109308672,
            "date": "2017-10-13",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 113712901,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107361553,
            "date": "2017-10-13",
            "pitches": 1,
            "notes": "4 bolts. Enjoying the permas ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113709912,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106188769,
            "date": "2017-09-24",
            "pitches": 1,
            "notes": "Little pumpy. Felt like something out of the Red ",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 113626014,
            "userStars": 3,
            "userRating": "5.9+"
        },
        {
            "routeId": 106618725,
            "date": "2017-09-24",
            "pitches": 1,
            "notes": "1 fall at crux before 3rd bolt. Has cool moves. Jesus Gaston ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113626013,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107834016,
            "date": "2017-09-24",
            "pitches": 1,
            "notes": "1 fall, foot slip on sloper. Lame. ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113626012,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107560400,
            "date": "2017-09-24",
            "pitches": 1,
            "notes": "Head game was a bit weak between 1 and 3",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 113626011,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107208763,
            "date": "2017-09-24",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 113626010,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106614620,
            "date": "2017-09-11",
            "pitches": 1,
            "notes": "RRG ",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 113582173,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106614611,
            "date": "2017-09-11",
            "pitches": 1,
            "notes": "Easier than the other 10as",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 113582171,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106921324,
            "date": "2017-09-11",
            "pitches": 1,
            "notes": "Added pockety Boulder start cause it looked cool ",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 113582170,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106783054,
            "date": "2017-09-11",
            "pitches": 1,
            "notes": "2 falls. Two move wonder. ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113582169,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106170048,
            "date": "2017-09-11",
            "pitches": 1,
            "notes": "Cool moves. Pinchy",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 113582167,
            "userStars": 3,
            "userRating": "5.10c"
        },
        {
            "routeId": 106065471,
            "date": "2017-09-11",
            "pitches": 1,
            "notes": "Fun. Classic RRG ",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 113582166,
            "userStars": 3,
            "userRating": "5.9+"
        },
        {
            "routeId": 106065461,
            "date": "2017-09-11",
            "pitches": 1,
            "notes": "Little pumpy. Awesome plates. ",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 113582165,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106189887,
            "date": "2017-09-11",
            "pitches": 1,
            "notes": "Staying left before the roof makes for a rude wake up. ",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 113582164,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106885726,
            "date": "2017-09-10",
            "pitches": 1,
            "notes": "Pumpy for a 9",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 113582172,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107132538,
            "date": "2017-09-10",
            "pitches": 1,
            "notes": "Dnf. PUMPY",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113582168,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107685747,
            "date": "2017-09-10",
            "pitches": 1,
            "notes": "Cool heel hook on arete ",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 113582163,
            "userStars": 3,
            "userRating": "5.10a"
        },
        {
            "routeId": 107684861,
            "date": "2017-09-10",
            "pitches": 1,
            "notes": "Crux before first bolt. Didn't stick clip",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 113582162,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106885779,
            "date": "2017-09-10",
            "pitches": 1,
            "notes": "2 hangs. Felt a lot easier than last time. Such cool moves ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113582156,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106061901,
            "date": "2017-09-09",
            "pitches": 1,
            "notes": "Milked the rest, found a gnarly arm bar ",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 113582161,
            "userStars": 3,
            "userRating": "5.10d"
        },
        {
            "routeId": 106064500,
            "date": "2017-09-09",
            "pitches": 1,
            "notes": "1 take 1 fall above fourth bolt ",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113582160,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 107321623,
            "date": "2017-09-09",
            "pitches": 1,
            "notes": "Short. Soft. Simple. ",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 113582159,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106968604,
            "date": "2017-09-09",
            "pitches": 1,
            "notes": "Soft. One move wonder ",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 113582158,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106968591,
            "date": "2017-09-09",
            "pitches": 1,
            "notes": "Soft 8",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 113582157,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106061906,
            "date": "2017-09-09",
            "pitches": 1,
            "notes": "Super easy this time around. Still 4 stars ",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 113582155,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106130303,
            "date": "2017-09-09",
            "pitches": 1,
            "notes": "Fantastic route. ",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 113582154,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106152681,
            "date": "2017-08-06",
            "pitches": 1,
            "notes": "Fell on roof pull. Laaaame",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113582251,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106152665,
            "date": "2017-08-06",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 113582246,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106152649,
            "date": "2017-08-06",
            "pitches": 1,
            "notes": "Tough top if you go up and not right. 1 hang",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113582240,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106152673,
            "date": "2017-08-06",
            "pitches": 1,
            "notes": "3 falls at Crux. 1 take on second half",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113582239,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 106000377,
            "date": "2017-07-25",
            "pitches": 4,
            "notes": "Bomber. Pleasant overhangs for first pitch. ",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 113391141,
            "userStars": 3,
            "userRating": "5.6"
        },
        {
            "routeId": 108459466,
            "date": "2017-06-09",
            "pitches": 1,
            "notes": "",
            "style": "",
            "leadStyle": "",
            "tickId": 113132511,
            "userStars": 1,
            "userRating": ""
        },
        {
            "routeId": 113132416,
            "date": "2017-06-09",
            "pitches": 1,
            "notes": "FA! Sketchy with no spot",
            "style": "",
            "leadStyle": "",
            "tickId": 113132506,
            "userStars": 2,
            "userRating": "V1"
        },
        {
            "routeId": 108459472,
            "date": "2017-06-09",
            "pitches": 1,
            "notes": "",
            "style": "",
            "leadStyle": "",
            "tickId": 113132501,
            "userStars": 2,
            "userRating": ""
        },
        {
            "routeId": 112394511,
            "date": "2017-04-01",
            "pitches": 1,
            "notes": "Lost a draw 2 from top. Too wet to do slab",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113132713,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 112393307,
            "date": "2017-04-01",
            "pitches": 1,
            "notes": "2 Falls",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 113132694,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106885779,
            "date": "2017-03-19",
            "pitches": 1,
            "notes": "TR Dirty",
            "style": "",
            "leadStyle": "",
            "tickId": 112568037,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106885721,
            "date": "2017-03-19",
            "pitches": 1,
            "notes": "",
            "style": "",
            "leadStyle": "",
            "tickId": 112568036,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 107807554,
            "date": "2017-03-19",
            "pitches": 1,
            "notes": "",
            "style": "",
            "leadStyle": "",
            "tickId": 112568035,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106026660,
            "date": "2017-03-16",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 112555326,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105880940,
            "date": "2017-03-16",
            "pitches": 1,
            "notes": "2 Falls",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 112555325,
            "userStars": 2,
            "userRating": ""
        }
    ],
    "success": 1
}