export default {
    "hardest": "5.11a",
    "average": "5.8",
    "ticks": [
        {
            "routeId": 106125099,
            "date": "2017-03-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 112553850,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106154626,
            "date": "2017-03-15",
            "pitches": 1,
            "notes": "2 falls. Very Soft 11",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 112553849,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 106125070,
            "date": "2017-03-15",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112553848,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 106085043,
            "date": "2017-03-12",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 112553847,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106061906,
            "date": "2017-03-12",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112553846,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 107537571,
            "date": "2017-03-12",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112553845,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106286280,
            "date": "2017-03-12",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112553844,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106085047,
            "date": "2017-03-12",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112553843,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 108524421,
            "date": "2017-03-12",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 112553842,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106130303,
            "date": "2017-03-12",
            "pitches": 1,
            "notes": "1 hang. Great route.",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 112553841,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105892929,
            "date": "2017-03-11",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112553840,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105882846,
            "date": "2017-03-11",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112553839,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105878619,
            "date": "2016-10-10",
            "pitches": 1,
            "notes": "Suuper juggy. Sit start for giggles",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 112227958,
            "userStars": 3,
            "userRating": "5.9-"
        },
        {
            "routeId": 105898433,
            "date": "2016-10-10",
            "pitches": 1,
            "notes": "DNF 3 hangs and a fall when throwing to the ferns left handed",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 112227929,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 105923846,
            "date": "2016-10-10",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 112227927,
            "userStars": 1,
            "userRating": ""
        },
        {
            "routeId": 105878204,
            "date": "2016-10-10",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 112227922,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 105962922,
            "date": "2016-10-09",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 112227918,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 105966659,
            "date": "2016-10-09",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 112227917,
            "userStars": 1,
            "userRating": ""
        },
        {
            "routeId": 105956200,
            "date": "2016-10-09",
            "pitches": 1,
            "notes": "DNF couldn't get crux",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 112227914,
            "userStars": 2,
            "userRating": ""
        },
        {
            "routeId": 106071435,
            "date": "2016-10-09",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 112227912,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 106058997,
            "date": "2016-10-08",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Redpoint",
            "tickId": 112227943,
            "userStars": 1,
            "userRating": ""
        },
        {
            "routeId": 107543321,
            "date": "2016-10-08",
            "pitches": 1,
            "notes": "Bit slabby for my taste",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 112227909,
            "userStars": 2,
            "userRating": ""
        },
        {
            "routeId": 106148885,
            "date": "2016-10-08",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Pinkpoint",
            "tickId": 112227908,
            "userStars": 2,
            "userRating": ""
        },
        {
            "routeId": 107543333,
            "date": "2016-10-08",
            "pitches": 1,
            "notes": "Mike pulled me off the crux but got it the second time",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 112227903,
            "userStars": 2,
            "userRating": ""
        },
        {
            "routeId": 106106801,
            "date": "2016-09-03",
            "pitches": 2,
            "notes": "Decked from the flake.",
            "style": "Lead",
            "leadStyle": "Fell\/Hung",
            "tickId": 112132612,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105840572,
            "date": "2016-09-03",
            "pitches": 1,
            "notes": "Tough but pulled it off",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112132608,
            "userStars": 2,
            "userRating": ""
        },
        {
            "routeId": 105821512,
            "date": "2016-09-03",
            "pitches": 2,
            "notes": "Mike's first Multi!",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112132606,
            "userStars": 4,
            "userRating": ""
        },
        {
            "routeId": 105799779,
            "date": "2016-09-03",
            "pitches": 1,
            "notes": "Little trickier than 5.7 at the buldge",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112132605,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 105799721,
            "date": "2016-09-03",
            "pitches": 1,
            "notes": "Great view, Great intro to the gunks",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112132603,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 106555494,
            "date": "2016-08-11",
            "pitches": 1,
            "notes": "SMALL crimps",
            "style": "",
            "leadStyle": "",
            "tickId": 112227936,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106555387,
            "date": "2016-08-11",
            "pitches": 1,
            "notes": "",
            "style": "",
            "leadStyle": "",
            "tickId": 112227934,
            "userStars": 1,
            "userRating": ""
        },
        {
            "routeId": 106064888,
            "date": "2016-08-11",
            "pitches": 1,
            "notes": "DNF. Stuck first 3 moves though. God that right hand blows",
            "style": "",
            "leadStyle": "",
            "tickId": 112227933,
            "userStars": 2,
            "userRating": ""
        },
        {
            "routeId": 105884815,
            "date": "2016-06-27",
            "pitches": 6,
            "notes": "Crack Climbing hurts. Pulled the crux on p3. Long day. Busted wrist",
            "style": "Follow",
            "leadStyle": "",
            "tickId": 111956240,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106092676,
            "date": "2016-06-19",
            "pitches": 2,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112132616,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 106092119,
            "date": "2016-06-19",
            "pitches": 1,
            "notes": "",
            "style": "Lead",
            "leadStyle": "Onsight",
            "tickId": 112132614,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105960760,
            "date": "2016-02-28",
            "pitches": 1,
            "notes": "",
            "style": "",
            "leadStyle": "",
            "tickId": 111996395,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105948063,
            "date": "2015-06-06",
            "pitches": 1,
            "notes": "",
            "style": "TR",
            "leadStyle": "",
            "tickId": 112227983,
            "userStars": 2,
            "userRating": ""
        },
        {
            "routeId": 107595440,
            "date": "2015-06-06",
            "pitches": 1,
            "notes": "Upper finger crack is TINY",
            "style": "",
            "leadStyle": "",
            "tickId": 112227977,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 106918048,
            "date": "2015-06-06",
            "pitches": 1,
            "notes": "Great slab, holds are where you need them",
            "style": "TR",
            "leadStyle": "",
            "tickId": 112227973,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 105941480,
            "date": "2015-06-06",
            "pitches": 1,
            "notes": "",
            "style": "TR",
            "leadStyle": "",
            "tickId": 112227969,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 105929544,
            "date": "2015-06-06",
            "pitches": 1,
            "notes": "",
            "style": "TR",
            "leadStyle": "",
            "tickId": 112227967,
            "userStars": 3,
            "userRating": ""
        },
        {
            "routeId": 106540643,
            "date": "2015-06-06",
            "pitches": 1,
            "notes": "",
            "style": "TR",
            "leadStyle": "",
            "tickId": 112227965,
            "userStars": 2,
            "userRating": ""
        },
        {
            "routeId": 105941458,
            "date": "2015-06-06",
            "pitches": 1,
            "notes": "",
            "style": "TR",
            "leadStyle": "",
            "tickId": 112227963,
            "userStars": 1,
            "userRating": ""
        },
        {
            "routeId": 105830468,
            "date": "2015-05-03",
            "pitches": 1,
            "notes": "",
            "style": "TR",
            "leadStyle": "",
            "tickId": 111996366,
            "userStars": -1,
            "userRating": ""
        },
        {
            "routeId": 105990554,
            "date": "2015-05-03",
            "pitches": 1,
            "notes": "",
            "style": "TR",
            "leadStyle": "",
            "tickId": 111996363,
            "userStars": -1,
            "userRating": ""
        }
    ],
    "success": 1
}